version: "3.9"

services:
  db:
    container_name: db
    build: ./
    ports:
      - "3303:3306"
    environment:
      - MYSQL_DATABASE=base
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin@123
      - MYSQL_ROOT_PASSWORD=root@123
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

